#!/usr/bin/env node
/* ============================================================================
   OneBrain Design System — token build
   Zero-dependency generator. Reads tokens.json (W3C DTCG, the single source of
   truth) and emits per-platform outputs into tokens/dist/:

     dist/tokens.css              namespaced --ob-* CSS vars + [data-theme=light]
     dist/tokens.js               CommonJS { dark, light } nested value object
     dist/tokens.d.ts             TypeScript types for the above
     dist/onebrain.tailwind.js    Tailwind preset (colors/elevation reference the
                                  --ob-* vars, so they stay theme-aware)
     dist/ios/OneBrainTokens.swift     SwiftUI color/spacing/radius/type constants
     dist/android/colors.xml           dark color resources  (res/values/)
     dist/android/colors-light.xml     light color resources (res/values-night→ see README)
     dist/android/dimens.xml           spacing/radius/size/font dimensions

   Run:  node tokens/build.js
   No npm install required (Node >= 14, only fs/path).
   ============================================================================ */

'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'tokens.json');
const DIST = path.join(ROOT, 'dist');

const src = JSON.parse(fs.readFileSync(SRC, 'utf8'));

/* -- 1. Walk the DTCG tree into a flat token list ------------------------- */
const rawMap = {};   // "color.bg" -> node
const tokens = [];   // { path, type, web } leaves, in document order

function walk(node, trail, inheritedType) {
  const type = node.$type || inheritedType;
  for (const key of Object.keys(node)) {
    if (key.startsWith('$')) continue;
    const child = node[key];
    if (child && typeof child === 'object' && '$value' in child) {
      const p = [...trail, key].join('.');
      rawMap[p] = child;
      tokens.push({
        path: p,
        type: child.$type || type,
        web: child.$extensions && child.$extensions.web,
      });
    } else if (child && typeof child === 'object') {
      walk(child, [...trail, key], child.$type || type);
    }
  }
}
walk(src, [], undefined);

/* -- 2. Resolve a token to its primitive value for a theme ---------------- */
function rawFor(node, theme) {
  if (theme === 'light' && node.$extensions && node.$extensions['com.onebrain.light'] != null) {
    return node.$extensions['com.onebrain.light'];
  }
  return node.$value;
}
function resolve(p, theme) {
  const node = rawMap[p];
  if (!node) return p;
  const v = rawFor(node, theme);
  if (typeof v === 'string') {
    const m = v.match(/^\{(.+)\}$/);
    if (m) return resolve(m[1], theme);
  }
  return v;
}

/* -- 3. Value formatters -------------------------------------------------- */
const cssVar = (p) => '--ob-' + p.replace(/\./g, '-');

function cssValue(tok, theme) {
  // font sizes carry a responsive clamp() for the web
  if (theme !== 'native' && tok.web) return tok.web;
  const v = resolve(tok.path, theme === 'native' ? 'dark' : theme);
  if (Array.isArray(v)) {
    return tok.type === 'cubicBezier' ? `cubic-bezier(${v.join(', ')})` : v.join(', ');
  }
  return String(v);
}

function jsValue(tok, theme) {
  const v = resolve(tok.path, theme);
  if (Array.isArray(v)) {
    return tok.type === 'cubicBezier' ? `cubic-bezier(${v.join(', ')})` : v.slice();
  }
  return v;
}

/* -- 4. dist/tokens.css --------------------------------------------------- */
function buildCss() {
  const dark = tokens.map((t) => `  ${cssVar(t.path)}: ${cssValue(t, 'dark')};`).join('\n');
  // light: only tokens whose resolved value actually differs from dark
  const lightLines = [];
  for (const t of tokens) {
    if (t.web) continue; // clamp() identical across themes
    const d = String(resolve(t.path, 'dark'));
    const l = String(resolve(t.path, 'light'));
    if (d !== l) lightLines.push(`  ${cssVar(t.path)}: ${cssValue(t, 'light')};`);
  }
  return `/* GENERATED by tokens/build.js from tokens.json — do not edit by hand.
   Namespaced --ob-* mirror of the design tokens. Optional: the canonical
   product sheet is colors_and_type.css; this file is the build artifact for
   tooling that wants a flat, generated var set. */
:root {
${dark}
}

[data-theme="light"] {
${lightLines.join('\n')}
}
`;
}

/* -- 5. dist/tokens.js + .d.ts -------------------------------------------- */
function nestTree(theme) {
  const tree = {};
  for (const t of tokens) {
    const segs = t.path.split('.');
    let cur = tree;
    for (let i = 0; i < segs.length - 1; i++) cur = cur[segs[i] ] || (cur[segs[i]] = {});
    cur[segs[segs.length - 1]] = jsValue(t, theme);
  }
  return tree;
}
function buildJs() {
  const dark = JSON.stringify(nestTree('dark'), null, 2).replace(/\n/g, '\n  ');
  const light = JSON.stringify(nestTree('light'), null, 2).replace(/\n/g, '\n  ');
  return `// GENERATED by tokens/build.js from tokens.json — do not edit by hand.
// OneBrain design tokens as plain JS values, resolved per theme.
// Usage (web / Electron / React Native / any JS):
//   const { dark, light } = require('@onebrain/tokens');   // or ./dist/tokens.js
//   element.style.background = dark.color.bg;
// Dimensions are CSS strings ("16px"); RN consumers can parseInt() them.
'use strict';
const tokens = {
  dark: ${dark},
  light: ${light},
};
module.exports = tokens;
module.exports.default = tokens;
`;
}
function buildDts() {
  const leafKeys = (groupPath) =>
    tokens
      .filter((t) => t.path.startsWith(groupPath + '.') && t.path.split('.').length === groupPath.split('.').length + 1)
      .map((t) => `    ${JSON.stringify(t.path.split('.').pop())}: string;`)
      .join('\n');
  return `// GENERATED by tokens/build.js — TypeScript types for dist/tokens.js
export interface OneBrainColorScale {
${leafKeys('color')}
}
export interface OneBrainThemeTokens {
  color: OneBrainColorScale;
  state: Record<string, string>;
  intent: Record<string, string>;
  gradient: Record<string, string>;
  font: {
    family: Record<string, string[]>;
    weight: Record<string, number>;
    size: Record<string, string>;
    leading: Record<string, number>;
    tracking: Record<string, string>;
  };
  space: Record<string, string>;
  size: Record<string, string>;
  radius: Record<string, string>;
  clipPath: Record<string, string>;
  shadow: Record<string, string>;
  motion: { duration: Record<string, string>; easing: Record<string, string> };
  opacity: Record<string, number>;
  zIndex: Record<string, number>;
}
declare const tokens: { dark: OneBrainThemeTokens; light: OneBrainThemeTokens };
export = tokens;
`;
}

/* -- 6. dist/onebrain.tailwind.js ----------------------------------------- */
function buildTailwind() {
  const ref = (group) =>
    tokens
      .filter((t) => t.path.startsWith(group + '.') && t.path.split('.').length === group.split('.').length + 1)
      .map((t) => `      ${JSON.stringify(t.path.split('.').pop())}: 'var(${cssVar(t.path)})',`)
      .join('\n');

  const literal = (group, fmt = (v) => `'${v}'`) =>
    tokens
      .filter((t) => t.path.startsWith(group + '.') && t.path.split('.').length === group.split('.').length + 1)
      .map((t) => `      ${JSON.stringify(t.path.split('.').pop())}: ${fmt(resolve(t.path, 'dark'), t)},`)
      .join('\n');

  const fontFamily = tokens
    .filter((t) => t.path.startsWith('font.family.'))
    .map((t) => `      ${JSON.stringify(t.path.split('.').pop())}: ${JSON.stringify(resolve(t.path, 'dark'))},`)
    .join('\n');

  const fontSize = tokens
    .filter((t) => t.path.startsWith('font.size.'))
    .map((t) => `      ${JSON.stringify(t.path.split('.').pop())}: '${t.web || resolve(t.path, 'dark')}',`)
    .join('\n');

  const spacing = tokens
    .filter((t) => t.path.startsWith('space.'))
    .map((t) => `      'ob-${t.path.split('.').pop()}': 'var(${cssVar(t.path)})',`)
    .join('\n');

  return `// GENERATED by tokens/build.js from tokens.json — Tailwind preset.
// Colors, elevation, spacing & durations reference the --ob-* CSS vars, so they
// stay theme-aware: load dist/tokens.css (or colors_and_type.css) alongside.
// Usage (tailwind.config.js):  module.exports = { presets: [require('./dist/onebrain.tailwind.js')] }
module.exports = {
  theme: {
    extend: {
      colors: {
${ref('color')}
${ref('state')}
${ref('chart')}
${ref('intent')}
      },
      fontFamily: {
${fontFamily}
      },
      fontSize: {
${fontSize}
      },
      spacing: {
${spacing}
      },
      screens: {
${literal('breakpoint')}
      },
      backgroundImage: {
${tokens.filter((t) => t.path.startsWith('gradient.')).map((t) => `        ${JSON.stringify('ob-' + t.path.split('.').pop())}: ${JSON.stringify(resolve(t.path, 'dark'))},`).join('\n')}
      },
      borderRadius: {
${literal('radius')}
      },
      boxShadow: {
        cta: 'var(--ob-shadow-glowCta)',
        cyan: 'var(--ob-shadow-glowCyan)',
        overlay: 'var(--ob-shadow-shadowOverlay)',
        'elev-1': 'var(--ob-shadow-elev1)',
        'elev-2': 'var(--ob-shadow-elev2)',
        'elev-3': 'var(--ob-shadow-elev3)',
      },
      transitionDuration: {
${literal('motion.duration', (v) => `'${String(v).replace('ms', '')}'`)}
      },
      transitionTimingFunction: {
${tokens.filter((t) => t.path.startsWith('motion.easing.')).map((t) => `        ${JSON.stringify(t.path.split('.').pop())}: 'cubic-bezier(${resolve(t.path, 'dark').join(', ')})',`).join('\n')}
      },
      zIndex: {
${literal('zIndex', (v) => `'${v}'`)}
      },
    },
  },
};
`;
}

/* -- 7. Native: iOS Swift -------------------------------------------------- */
const swiftName = (p) => p.split('.').pop().replace(/[^a-zA-Z0-9]/g, '');
function swiftColors(theme) {
  return tokens
    .filter((t) => t.type === 'color' && (t.path.startsWith('color.') || t.path.startsWith('state.') || t.path.startsWith('intent.')))
    .map((t) => `        static let ${swiftName(t.path)} = Color(hex: "${resolve(t.path, theme)}")`)
    .join('\n');
}
function pxNum(p) { return String(resolve(p, 'dark')).replace('px', ''); }
function buildSwift() {
  const space = tokens.filter((t) => t.path.startsWith('space.'))
    .map((t) => `        static let s${t.path.split('.').pop()}: CGFloat = ${pxNum(t.path)}`).join('\n');
  const radius = tokens.filter((t) => t.path.startsWith('radius.'))
    .map((t) => `        static let ${swiftName(t.path) || 'r'}: CGFloat = ${pxNum(t.path)}`).join('\n');
  const fsize = tokens.filter((t) => t.path.startsWith('font.size.'))
    .map((t) => `        static let ${t.path.split('.').pop()}: CGFloat = ${pxNum(t.path)}`).join('\n');
  const fweight = tokens.filter((t) => t.path.startsWith('font.weight.'))
    .map((t) => { const k = t.path.split('.').pop(); return `        static let ${k} = Font.Weight.${k}`; }).join('\n');
  const bp = tokens.filter((t) => t.path.startsWith('breakpoint.'))
    .map((t) => `        static let ${t.path.split('.').pop()}: CGFloat = ${pxNum(t.path)}`).join('\n');
  return `// GENERATED by tokens/build.js from tokens.json — SwiftUI tokens (iOS app surface).
// Drop into an iOS target. Color(hex:) accepts #RRGGBB or #RRGGBBAA.
import SwiftUI

public enum OneBrain {
    public enum ColorsDark {
${swiftColors('dark')}
    }
    public enum ColorsLight {
${swiftColors('light')}
    }
    public enum Space {
${space}
    }
    public enum Radius {
${radius}
    }
    public enum FontSize {
${fsize}
    }
    public enum FontWeight {
${fweight}
    }
    public enum Breakpoint {
${bp}
    }
}

public extension Color {
    init(hex: String) {
        var s = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        if s.count == 6 { s += "FF" }
        var n: UInt64 = 0
        Scanner(string: s).scanHexInt64(&n)
        let r = Double((n & 0xFF000000) >> 24) / 255
        let g = Double((n & 0x00FF0000) >> 16) / 255
        let b = Double((n & 0x0000FF00) >> 8) / 255
        let a = Double(n & 0x000000FF) / 255
        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
    }
}
`;
}

/* -- 8. Native: Android XML ----------------------------------------------- */
const andName = (p) => 'ob_' + p.replace(/\./g, '_');
// web #RRGGBB / #RRGGBBAA  ->  android #AARRGGBB
function androidHex(v) {
  let s = String(v).replace('#', '');
  if (s.length === 6) return '#' + s.toUpperCase();
  if (s.length === 8) return '#' + (s.slice(6, 8) + s.slice(0, 6)).toUpperCase();
  return '#' + s.toUpperCase();
}
function androidColors(theme) {
  const rows = tokens
    .filter((t) => t.type === 'color' && (t.path.startsWith('color.') || t.path.startsWith('state.') || t.path.startsWith('intent.')))
    .map((t) => `    <color name="${andName(t.path)}">${androidHex(resolve(t.path, theme))}</color>`)
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by tokens/build.js — ${theme} color resources -->\n<resources>\n${rows}\n</resources>\n`;
}
function buildAndroidDimens() {
  const dim = (group, prefix) =>
    tokens.filter((t) => t.path.startsWith(group + '.'))
      .map((t) => `    <dimen name="${prefix}_${t.path.split('.').pop()}">${pxNum(t.path)}dp</dimen>`)
      .join('\n');
  const sp = tokens.filter((t) => t.path.startsWith('font.size.'))
    .map((t) => `    <dimen name="ob_font_${t.path.split('.').pop()}">${pxNum(t.path)}sp</dimen>`)
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by tokens/build.js — spacing / radius / size / breakpoint / font dimensions -->\n<resources>\n${dim('space', 'ob_space')}\n${dim('radius', 'ob_radius')}\n${dim('size', 'ob_size')}\n${dim('breakpoint', 'ob_bp')}\n${sp}\n</resources>\n`;
}

/* -- 9. Write everything -------------------------------------------------- */
function write(rel, content) {
  const out = path.join(DIST, rel);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, content);
  return rel;
}

const written = [
  write('tokens.css', buildCss()),
  write('tokens.js', buildJs()),
  write('tokens.d.ts', buildDts()),
  write('onebrain.tailwind.js', buildTailwind()),
  write('ios/OneBrainTokens.swift', buildSwift()),
  write('android/colors.xml', androidColors('dark')),
  write('android/colors-light.xml', androidColors('light')),
  write('android/dimens.xml', buildAndroidDimens()),
];

console.log(`OneBrain tokens: ${tokens.length} tokens -> ${written.length} files`);
for (const w of written) console.log('  dist/' + w);
